---
platform: windows

inputs:
- name: concourse
- name: ci
- name: final-version
  optional: true

outputs:
- name: fly-windows

caches:
- path: gopath
- path: tmp

run:
  path: powershell
  args: [ci/tasks/scripts/fly-build.ps1]
