resource_types:
- name: concourse-pipeline
  type: registry-image
  source:
    repository: concourse/concourse-pipeline-resource

resources:
- name: pipelines
  type: git
  icon: github-circle
  source:
    uri: https://github.com/concourse/ci
    paths:
    - pipelines

- name: baggageclaim-ci
  type: git
  icon: github-circle
  source:
    uri: https://github.com/concourse/baggageclaim
    paths: [ci]

- name: concourse-for-k8s
  type: git
  icon: github-circle
  source:
    uri: https://github.com/pivotal/concourse-for-k8s
    paths:
    - ci

- name: ruby-alpine-image
  type: registry-image
  source:
    repository: ruby
    tag: rc-alpine

- name: oxygen-mask
  type: git
  icon: github-circle
  source:
    uri: https://github.com/concourse/oxygen-mask

- name: prod
  type: concourse-pipeline
  icon: pipe
  source:
    target: https://nci.concourse-ci.org
    teams:
    - name: main
      username: ((basic_auth.username))
      password: ((basic_auth.password))
    - name: resources
      username: ((basic_auth.username))
      password: ((basic_auth.password))
    - name: monitoring-hush-house
      username: ((basic_auth.username))
      password: ((basic_auth.password))

jobs:
- name: reconfigure-resource-pipelines
  plan:
  - get: pipelines
    trigger: true
  - task: render-resource-templates
    file: pipelines/tasks/render-resource-pipeline-templates.yml
    params:
      RESOURCES: |
        git
        time
        docker-image
        registry-image
        cf
        bosh-io-release
        bosh-io-stemcell
        tracker
        hg
        github-release
        semver
        s3
        concourse-pipeline
        pool
        datadog-event
        mock
  - put: prod
    inputs: [rendered_pipelines]
    params:
      pipelines:
        - name: git
          team: resources
          config_file: rendered_pipelines/git.yml
        - name: time
          team: resources
          config_file: rendered_pipelines/time.yml
        - name: docker-image
          team: resources
          config_file: rendered_pipelines/docker-image.yml
        - name: registry-image
          team: resources
          config_file: rendered_pipelines/registry-image.yml
        - name: cf
          team: resources
          config_file: rendered_pipelines/cf.yml
        - name: bosh-io-release
          team: resources
          config_file: rendered_pipelines/bosh-io-release.yml
        - name: bosh-io-stemcell
          team: resources
          config_file: rendered_pipelines/bosh-io-stemcell.yml
        - name: tracker
          team: resources
          config_file: rendered_pipelines/tracker.yml
        - name: hg
          team: resources
          config_file: rendered_pipelines/hg.yml
        - name: github-release
          team: resources
          config_file: rendered_pipelines/github-release.yml
        - name: semver
          team: resources
          config_file: rendered_pipelines/semver.yml
        - name: s3
          team: resources
          config_file: rendered_pipelines/s3.yml
        - name: concourse-pipeline
          team: resources
          config_file: rendered_pipelines/concourse-pipeline.yml
        - name: pool
          team: resources
          config_file: rendered_pipelines/pool.yml
        - name: datadog-event
          team: resources
          config_file: rendered_pipelines/datadog-event.yml
        - name: mock
          team: resources
          config_file: rendered_pipelines/mock.yml

- name: reconfigure-pipelines
  plan:
  - get: pipelines
    trigger: true
  - get: baggageclaim-ci
    trigger: true
  - get: concourse-for-k8s
    trigger: true
  - put: prod
    params:
      pipelines:
      - name: reconfigure-pipelines
        team: main
        config_file: pipelines/pipelines/reconfigure.yml
      - name: concourse
        team: main
        config_file: pipelines/pipelines/concourse.yml
      - name: prs
        exposed: true
        team: main
        config_file: pipelines/pipelines/prs.yml
      - name: helm-prs
        team: main
        config_file: pipelines/pipelines/helm-prs.yml
        vars:
          pr_base_branch: master
          # Why a release branch and not master?
          # A: We want to test pr's against the last stable release of Concourse,
          # in particular we care about which version of k8s-topgun we use.
          # Dev flags are tested in the main pipeline with other unreleased code
          concourse_base_branch: release/5.7.x
          concourse_image_tag: latest
      - name: helm-prs-5.5.x
        team: main
        config_file: pipelines/pipelines/helm-prs.yml
        vars:
          pr_base_branch: release/5.5.x
          concourse_base_branch: release/5.5.x
          concourse_image_tag: 5.5
      - name: helm-prs-5.7.x
        team: main
        config_file: pipelines/pipelines/helm-prs.yml
        vars:
          pr_base_branch: release/5.7.x
          concourse_base_branch: release/5.7.x
          concourse_image_tag: 5.7
      - name: baggageclaim
        exposed: true
        team: main
        config_file: baggageclaim-ci/ci/pipeline.yml
      - name: bosh-cleanup
        team: main
        config_file: pipelines/pipelines/bosh-cleanup.yml
      - name: wings
        team: main
        config_file: pipelines/pipelines/wings.yml
      - name: norsk-mirror
        team: main
        config_file: pipelines/pipelines/norsk-mirror.yml
      - name: release-5.2.x
        team: main
        exposed: true
        config_file: pipelines/pipelines/release.yml
        vars:
          release_major: "5"
          release_minor: "5.2"
          concourse_smoke_deployment_name: "concourse-smoke-5-2"
          use_external_linker: true
      - name: release-5.5.x
        team: main
        exposed: true
        config_file: pipelines/pipelines/release.yml
        vars:
          release_major: "5"
          release_minor: "5.5"
          concourse_smoke_deployment_name: "concourse-smoke-5-5"
          use_external_linker: false
      - name: release-5.7.x
        team: main
        exposed: true
        config_file: pipelines/pipelines/release.yml
        vars:
          release_major: "5"
          release_minor: "5.7"
          concourse_smoke_deployment_name: "concourse-smoke-5-7"
          use_external_linker: false
      - name: algorithm-v3
        team: main
        config_file: pipelines/pipelines/branch.yml
        vars:
          branch_name: algorithm-v3
          environment: algorithm
      - name: runtime-drills
        team: main
        config_file: pipelines/pipelines/branch.yml
        vars:
          branch_name: master
          environment: runtime-drills
      - name: set-zstd-drills-env
        team: main
        config_file: pipelines/pipelines/branch.yml
        vars:
          branch_name: use_zstd
          environment: use-zstd
      - name: enterprise-helm-chart
        team: main
        config_file: concourse-for-k8s/ci/pipeline.yml
      - name: prod-db-backup
        team: main
        config_file: pipelines/pipelines/prod-db-backup.yml
      - name: prod-db-restore-verify
        team: main
        config_file: pipelines/pipelines/prod-db-restore-verify.yml

- name: reconfigure-monitoring-pipeline
  plan:
  - get: oxygen-mask
    trigger: true
  - get: ruby-alpine-image
  - task: generate-monitor-yml
    image: ruby-alpine-image
    config:
      platform: linux
      inputs:
      - name: oxygen-mask
      outputs:
      - name: oxygen-mask
      run:
        dir: oxygen-mask
        path: sh
        args:
        - -c
        - |
          erb monitor.yml > gen-monitor.yml
  - put: prod
    params:
      pipelines:
      - name: monitoring-stats
        team: monitoring-hush-house
        config_file: oxygen-mask/gen-monitor.yml
        vars:
          atc_url: https://hush-house.pivotal.io
          interval: 30s
          username: ((basic_auth.username))
          password: ((basic_auth.password))
          team_name: main
          pipeline_name: monitoring
          datadog_api_key: ((datadog_api_key))
          github_access_token: ((concourse_github_dummy.access_token))

